name: Ron Blog
email: lshxin89@126.com
author: Ron
url: https://www.themis.wiki
resume_site: https://www.themis.wiki
baseurl: 
description: 技术是认知的工具
github_username: KKLater
github: https://github.com/KKLater
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : e253949f731657ca7a95
    clientSecret : 6e3a2c00a320b2628c4e84ad4ae0a30f60f2c826
    repo : kklater.github.io
    owner : Ron
    admin : Ron
